# This file is used for development
version: '3.0'
services:
  pg:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: application
      POSTGRES_PASSWORD: km8RiybqtMAh
